# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: Default

steps:

- script: echo "Running on $(AGENT_OS)"
  displayName: 'Display Agent OS'
